apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3exporter.fullname" . }}
  labels:
    {{- include "s3exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: probe
      protocol: TCP
      name: probe
  selector:
    {{- include "s3exporter.selectorLabels" . | nindent 4 }}
